namespace: containers
name: podman
<<<<<<< HEAD
version: 1.19.2
=======
version: 1.20.0
>>>>>>> ed22d92 (feat: Create podman_build modules to build using quadlet)
readme: README.md
authors:
  - Sagi Shnaidman <sshnaidm@redhat.com>
  - Ansible team
description: Podman container Ansible modules
license: GPL-3.0-or-later
tags:
  - containers
  - podman
  - libpod
  - buildah
  - docker
dependencies: {}
repository: https://github.com/containers/ansible-podman-collections
documentation: https://docs.ansible.com/ansible/latest/collections/containers/podman/
homepage: https://github.com/containers/ansible-podman-collections
issues: https://github.com/containers/ansible-podman-collections/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - ci
  - tests/output
  - build_artifact
  - "*.tar.gz"
  - ".gitignore"
  - ".history"
  - ".vscode"
  - ".idea"
  - ".github"
  - contrib
  - galaxy.yml.in
  - importer_result.json
